### PR TITLE
Correct Images scales (Plone 4) & add note on plone.css

### PR DESCRIPTION
**Pull request by djowett**
Sorry there's 2 changes in one pull request - bad form really, but the comments will let you know how incredibly ;-) reasonable & acceptable they are

### CODE REVIEW

**Comment by hvelarde** [comment]
this part of the documentation is wrong: `plone.namedfile` has nothing to do with image scales but with fields and wrapper objects for storing a file with a filename or an image with a filename, as you can see in the documentation.

`plone.app.imaging` does the work no matter the content type is Dexterity or Archetypes.

**Comment by davisagli** [comment]
@hvelarde Actually plone.namedfile does indeed provide the implementation of the @@images view that is used for Dexterity content, and the one in plone.app.imaging is only used for Archetypes.

**Comment by djay** [comment]
it's pretty messy at the moment. You can see all the different packages I had to patch to support file and image downloading in 4.3 via xsendfile.

https://github.com/collective/collective.xsendfile/blob/dx_support/collective/xsendfile/configure.zcml

and that doesn't even include image scale urls yet.

**Comment by hvelarde** [comment]
@davisagli good to know, we need to update `plone.namedfile` documentation then :-)

**Pull request merged**
