### PR TITLE
redistribute tutorials into relevant sections

### PR DESCRIPTION
**Pull request by djay**
rationale is tutorials section is new content should be placed carefully into the manual to make sure its not duplicated and all related content is found near each other as much as possible so readers can discover the information they are after. Generic sections such as "tutorials" lead to the opposite.

### CODE REVIEW

**Comment by bdbaddog** [comment]
I'm not sure this isn't really a bikesheading issue...

**Comment by djay** [comment]
Whats a bikesheading issue?

**Comment by bdbaddog** [comment]
Whether the tutorials should be grouped together, or grouped with their topics.

**Comment by bdbaddog** [comment]
http://bikeshed.com/

**Comment by djay** [comment]
I don't get your complaint. Are you saying it's too smaller a change
so there in no point in discussing it, just do it?
Or are you saying you don't care where tutorials go in which case why
comment? This change doesn't prevent tutorials being created and the
sooner it's done the less painful it will be.

**Comment by bdbaddog** [comment]
I'm saying that changing the organization is somewhat arbitrary as it's arguable that it's better to keep all the tutorials together, as well as arguable that it's better to put them with the related content. (Thus bikesheading)

In which case, it may be better to not change the organization.

Since it's not a clear win for the manual to make a change, I'm suggesting that you simply leave the content as it is, and retract your pull request.

**Comment by djay** [comment]
I did the work to move the tutorials for a good reason as outlined above. You might not agree, but since you feel the need to argue against it even though you don't care either way... isn't that bikeshedding?
The choice doesn't seem arbitrary at all to me. The problem with plone is not too little documentation but rather too much conflicting documentation. Without clear guidance as to where people should contribute new content then the manual will become a dumping ground with different people choosing to contribute new documentation rather than rewriting old documentation. The tutorials section provides the perfect place to do that since you can repeat every topic already covered in the other sections. 
Is it really worth this much discussion? If there is going to be resistance every time someone wants to clean the manual as opposed to add new content then it will become a dumping ground and we will end up the knowledge base all over again.
Once I've got past this change I'll start to remove duplicate content from those tutorials and the other documentation in those sections so it's less confusing to the reader.

**Comment by miohtama** [comment]
Done.

**Pull request closed without merging**
