### PR TITLE
Easier solution for log rotation

### PR DESCRIPTION
**Pull request by sureshvv**
Just been implemented in the buildout recipe

### CODE REVIEW

**Comment by encolpe** [comment]
You should wait the next  release of the recipe ([at least plone.recipe.zope2instance 4.2.5](http://pypi.python.org/pypi/plone.recipe.zope2instance/4.2.5])) before to merge this one.

**Comment by sureshvv** [comment]
ok.. let me get on that
Date: Thu, 20 Sep 2012 00:06:11 -0700

**Comment by sureshvv** [comment]
Hanno has made a new release... Thanks Hanno... So go ahead and merge it in
Thanks!

Date: Thu, 20 Sep 2012 00:06:11 -0700

**Comment by jean** [comment]
This is probably a good place to consider using the Sphinx `.. versionadded:: version` (and following) directives:
http://sphinx.pocoo.org/markup/para.html#directive-versionadded

**Comment by miohtama** [comment]
Is this going to Plone 4.3? I am not sure what version to support here :)

**Comment by jean** [comment]
Hmm, it depends a bit on the focus of the documentation. 

The change pertains to `plone.recipe.zope2instance` version 4.2.5, so if the documentation is supposed to tell you that you're OK with that version of the recipe, then `versionadded` should apply to the recipe. 

However if that recipe is part of Plone 4.3 and the documentation is just supposed to tell you that you're OK with that Plone, then `versionadded` can apply to Plone. 

What it applies to should be clear from the context. It looks like Sphinx assumes you're writing about one single software project, so `versionadded` doesn't allow you to specify the version of _what_. But I don't think that's a useful assumption with `collective.developermanual`, as we're writing about many different software components.

**Comment by sureshvv** [comment]
i have indicated the minimum version number of p.r.zope2instance in the doc.

**Pull request merged**
