### PR TITLE
First attempt at Hello World tutorial

### PR DESCRIPTION
**Pull request by cullerton**
Hey Folks,

Here's an attempt at a Hello World tutorial. I made 3 changes to the getstarted area. 
- removed helloworld.rst
- created a directory named helloworld (and added index.rst and some images)
- edited getstarted/index.rst to point to my new directory instead of helloworld.rst

Mike

### CODE REVIEW

**Comment by eleddy** [comment]
MIKE (hi)! zupo and I literally 3 days ago started working on something very similar. We should collaborate - ping us in irc maybe?

**Comment by eleddy** [comment]
oh, - check out https://github.com/collective/collective.todoapp    I think there is a small piece of overlap but if we focus the 2 tutorials then we won't overwrite eachother

**Comment by cullerton** [comment]
It looks like my image links are broken. I'll try to fix that.

**Comment by jean** [comment]
Dang, I still wanted to ask to use `=====` as top-level heading, as `=====` is obviously heavier than `-----`. 

Also wanted to point out that `.. todo:: Some todo item` is available for todos.

**Comment by djay** [comment]
On 21/08/2012, at 3:18 AM, Elizabeth Leddy notifications@github.com wrote:

oh, - check out https://github.com/collective/collective.todoapp I think
there is a small piece of overlap but if we focus the 2 tutorials then we
won't overwrite eachother

Coincidence but as of Thursday the plugin in
https://github.com/collective/collective.listingviews if used in that
todoapp tutorial would vastly simplify it. You wouldn't need to touch the
file system till the last chapter.

 —
Reply to this email directly or view it on
GitHubhttps://github.com/collective/collective.developermanual/pull/61#issuecomment-7876421.

**Comment by eleddy** [comment]
We actually pulled the todo app into plone so that it gets tested/versioned with every plone release. Would love to simplify but in general we are trying to stick to whats in core. plone.api will be plipped - are you planning on plipping the contentviews?

Liz

**Comment by aclark4life** [comment]
+1 re: todo app in plone core

**Comment by djay** [comment]
On 08/09/2012, at 9:39 AM, Elizabeth Leddy wrote:

> We actually pulled the todo app into plone so that it gets tested/ 
> versioned with every plone release. Would love to simplify but in  
> general we are trying to

sorry wasn't suggesting rewriting the tutorial, it was more a comment  
that I seem to be on the right track :)

> stick to whats in core. plone.api will be plipped -

I agree with sticking to the core.

> are you planning on plipping the contentviews?

yes-ish. My vague plan was something like this.
1. build something general but solved specific cases for my current  
clients
2. see if others use it and refine based on that (e.g. your UI  
suggestions)
3. get it into core as the primary listing tile in deco (one reason  
I'd like to go to seasprint)

I didn't really want to follow the path of PLIPing something that  
wasn't fully tried in production many times over but I do see  
listingviews as being a core concept to plone going forward. or  
something very similar.

> Liz
> 
> On Sep 7, 2012, at 4:17 PM, Dylan Jay wrote:
> 
> > On 21/08/2012, at 3:18 AM, Elizabeth Leddy

**Comment by djay** [comment]
On 08/09/2012, at 11:09 AM, Dylan Jay wrote:

> On 08/09/2012, at 9:39 AM, Elizabeth Leddy wrote:
> 
> > We actually pulled the todo app into plone so that it gets tested/ 
> > versioned with every plone release. Would love to simplify but in  
> > general we are trying to
> 
> sorry wasn't suggesting rewriting the tutorial, it was more a  
> comment that I seem to be on the right track :)
> 
> > stick to whats in core. plone.api will be plipped -
> 
> I agree with sticking to the core.
> 
> > are you planning on plipping the contentviews?
> 
> yes-ish. My vague plan was something like this.
> 1. build something general but solved specific cases for my current  
> clients
> 2. see if others use it and refine based on that (e.g. your UI  
> suggestions)
> 3. get it into core as the primary listing tile in deco (one reason  
> I'd like to go to seasprint)
> 
> I didn't really want to follow the path of PLIPing something that  
> wasn't fully tried in production many times over but I do see  
> listingviews as being a core concept to plone going forward. or  
> something very similar.

btw, I'm open to the idea of pliping it as is earlier if others think  
so.

**Pull request merged**
