### PR TITLE
Update source/hosting/restarts.rst

### PR DESCRIPTION
**Pull request by jianaijun**

### CODE REVIEW

**Comment by svx** [comment]
I would like to make your change an extra or second example, since your change is doing far more than just a restart, so i would like to add it as another option

**Comment by jianaijun** [comment]
Good

2013/1/31 sven notifications@github.com

**Comment by svx** [comment]
do you want to do it ? otherwise i can do it, tomorrow or during the weekend

**Comment by jianaijun** [comment]
English is not my native language.
You can do it.

2013/1/31 sven notifications@github.com

**Comment by jianaijun** [comment]
English is not my native language.
I'm sure you can do better than me.

2013/2/1 Jian Aijun jianaijun@gmail.com

**Pull request merged**
